Object.defineProperty(exports, '__esModule', { value: true })
exports.resourceData = [
  {
    TaskID: 1,
    TaskName: 'Project initiation',
    StartDate: new Date('03/29/2021'),
    EndDate: new Date('04/21/2021'),
    subtasks: [
      {
        TaskID: 2,
        TaskName: 'Prepare Business Case',
        StartDate: new Date('03/29/2021'),
        Duration: 2,
        Progress: 30,
        work: 16,
        resources: [{ resourceId: 1, unit: 70 }, 6],
      },
      {
        TaskID: 3,
        TaskName: 'Requirement Analysis',
        StartDate: new Date('03/29/2021'),
        Duration: 4,
        resources: [2, 3, 5],
        work: 96,
      },
      {
        TaskID: 4,
        TaskName: 'Software test approval',
        StartDate: new Date('03/29/2021'),
        Duration: 1,
        work: 16,
        resources: [8, { resourceId: 9, unit: 50 }],
        Progress: 30,
      },
    ],
  },
  {
    TaskID: 5,
    TaskName: 'Project estimation',
    StartDate: new Date('03/29/2021'),
    EndDate: new Date('04/21/2021'),
    subtasks: [
      {
        TaskID: 6,
        TaskName: 'High Level Design Document',
        StartDate: new Date('03/29/2021'),
        Duration: 3,
        Progress: 30,
        resources: [{ resourceId: 4, unit: 50 }],
        work: 30,
      },
      {
        TaskID: 7,
        TaskName: 'Components Designing',
        StartDate: new Date('04/01/2021'),
        Duration: 3,
        work: 48,
        resources: [4, 8],
        Predecessor: '6FS',
      },
      {
        TaskID: 8,
        TaskName: 'Estimation approval',
        StartDate: new Date('04/01/2021'),
        Duration: 2,
        work: 60,
        resources: [12, { resourceId: 5, unit: 70 }],
      },
      {
        TaskID: 9,
        TaskName: 'Estimation approval',
        StartDate: new Date('04/01/2021'),
        Duration: 2,
        work: 60,
      },
    ],
  },
  {
    TaskID: 10,
    TaskName: 'Sign contract',
    StartDate: new Date('04/01/2021'),
    Duration: 1,
    Progress: 30,
    resources: [12],
    work: 24,
  },
]
exports.resourceDetails = [
  { resourceId: 1, resourceName: 'Vishvesh' },
  { resourceId: 2, resourceName: 'Akshay' },
  { resourceId: 3, resourceName: 'Nisha' },
  { resourceId: 4, resourceName: 'Ankita' },
  { resourceId: 5, resourceName: 'Rahul' },
  { resourceId: 6, resourceName: 'Sachin' },
  { resourceId: 7, resourceName: 'Swati' },
  { resourceId: 8, resourceName: 'Manisha' },
  { resourceId: 9, resourceName: 'Parth' },
  { resourceId: 10, resourceName: 'Surabhi' },
  { resourceId: 11, resourceName: 'Kiran' },
  { resourceId: 12, resourceName: 'Shilpa' },
]
